[project]
name = "word2vec-numpy"
version = "0.1.0"
description = "Word2Vec algorithm implementation in Python using NumPy"
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "numpy>=2.4.2",
    "pytest>=9.0.2",
]
